"""empty message

Revision ID: 80a7a6bd8bed
Revises: a5cffa318ac2
Create Date: 2025-09-25 16:07:30.059983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a7a6bd8bed'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('FirstName', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('LastName', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['LastName'])
        batch_op.create_unique_constraint(None, ['FirstName'])
        batch_op.drop_column('password')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('LastName')
        batch_op.drop_column('FirstName')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
